apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: us-east-1-danilicious-chimny-production
  namespace: argocd
  annotations:
    godsAppName: chimny
    godsCluster: us-east-1
    godsTeamName: danilicious
    godsEnv: production
    godsEnvConfigurationVersion: 00dc622d54ff519fe917a72495f68d2310eecf8e
spec:
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: 'https://github.com/gitopsdevsolutions/opinionated-charts'
    path: 'charts/base-app'
    targetRevision: main
    helm:
      values: |
        env:
          DESCRIPTION: "CHIMNY CHIMNY YEA CHIMNY YEA CHIMNY YEA, SWALALA"
        
        image: gitopsdevsolutions/lifecycle-ui
        tag: latest
        createdAt: 2022-01-03 01:25:35 +0000 UTC
  destination:
    server: https://kubernetes.default.svc
    namespace: danilicious-production