apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: us-east-1-danilicious-jobisgood-production
  namespace: argocd
  annotations:
    godsAppName: jobisgood
    godsApplicationType: Job
    godsCluster: us-east-1
    godsTeamName: danilicious
    godsEnv: production
    godsEnvConfigurationVersion: f0f1398b98876e5923bfb40c3109077493441e51
    godsImageTag: latest
spec:
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: 'https://github.com/gitopsdevsolutions/opinionated-charts'
    path: 'charts/base-job'
    targetRevision: main
    
    helm:
      values: |
        env:
          DESCRIPTION: "FACKALACA DING DONG, DONG DING FACKALACA"
        image: hello-world
        tag: latest
        createdAt: 2021-09-23 23:47:57 +0000 UTC
  destination:
    server: https://kubernetes.default.svc
    namespace: danilicious-production