apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: us-east-1-third-party-secret-production
  namespace: argocd
  annotations:
    godsAppName: secret
    
    godsCluster: us-east-1
    godsTeamName: third-party
    godsEnv: production
    godsEnvConfigurationVersion: 868bbe5bb7227cf6554c4749881fe1280d51d6cb
spec:
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: 'https://github.com/gitopsdevsolutions/opinionated-charts'
    path: 'charts/base-app'
    targetRevision: main
    helm:
      values: |
        404 page not found
        image: ""
        tag: 2.6.5-alpine
        createdAt: 2021-11-19 23:42:01 +0000 UTC
  destination:
    server: https://kubernetes.default.svc
    namespace: third-party-production