apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: manifests
    meta.helm.sh/release-namespace: gitopscd
  name: manifests
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: a-role-binding
  namespace: manifests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: a-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: manifests
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: a-role
  namespace: manifests
rules:
  - apiGroups:
      - jetstream.nats.io
    resources:
      - streams
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - delete
      - patch
---
apiVersion: v1
kind: Secret
metadata:
  name: wanna-know-a-secret
  namespace: manifests
type: Opaque
data:
  THIS_IS_THE_SECRET: <path:gitopsdevsolutions#docker-registry-auth>