apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: us-east-1-carmelonson-krassovski-production
  namespace: argocd
  annotations:
    godsAppName: krassovski
    godsCluster: us-east-1
    godsTeamName: carmelonson
    godsEnv: production
    godsEnvConfigurationVersion: 132869a0ddf396bc2fa2d1f499f9d1d5936dd635
spec:
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: 'https://github.com/gitopsdevsolutions/opinionated-charts'
    path: 'charts/base-cron-job'
    targetRevision: main
    helm:
      values: |
        secrets:
          GODS_AWS_ACCESS_KEY: "<path:gitopsdevsolutions#aws_access_key_id>"
          GODS_AWS_SECRET_ACCESS_KEY: "<path:gitopsdevsolutions#aws_secret_key>"
        env:
          GODS_AWS_REGION: "us-east-1"
          IMA_SHEL_DANNY_LOCATION: ALAI
          IMA_SHEL_DANNY_ROLE: BABY_GIRL
        interval: "*/1 * * * *"
        image: gitopsdevsolutions/krassovski
        tag: latest
        createdAt: 2022-01-10 11:36:11 +0000 UTC
  destination:
    server: https://kubernetes.default.svc
    namespace: carmelonson-production