apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: us-east-1-carmelonson-krassovski-production
  namespace: argocd
  annotations:
    godsAppName: krassovski
    godsCluster: us-east-1
    godsTeamName: carmelonson
    godsEnv: production
    godsEnvConfigurationVersion: bacbf5f762d484498e547c04e524a441fa010b7f
spec:
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: 'https://github.com/gitopsdevsolutions/opinionated-charts'
    path: 'charts/base-app'
    targetRevision: main
    helm:
      values: |
        secrets:
          GODS_AWS_ACCESS_KEY: "<path:gitopsdevsolutions#aws_access_key_id>"
          GODS_AWS_SECRET_ACCESS_KEY: "<path:gitopsdevsolutions#aws_secret_key>"
        env:
          GODS_AWS_REGION: "us-east-1"
          IMA_SHEL_DANNY_LOCATION: ALAI
          IMA_SHEL_DANNY_ROLE: BABY_GIRL
        
        image: gitopsdevsolutions/krassovski
        tag: latest
        createdAt: 2022-01-02 20:25:56 +0000 UTC
  destination:
    server: https://kubernetes.default.svc
    namespace: carmelonson-production