apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: us-east-1-danilicious-chimmi-production
  namespace: argocd
  annotations:
    godsAppName: chimmi
    godsCluster: us-east-1
    godsTeamName: danilicious
    godsEnv: production
    godsEnvConfigurationVersion: 0f25912c796f2aa572a7edc6be121a2aab47e010
spec:
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: 'https://github.com/gitopsdevsolutions/opinionated-charts'
    path: 'charts/base-cron-job'
    targetRevision: main
    helm:
      values: |
        env:
          DESCRIPTION: "CHIMMI CHIMMI YEA CHIMMI YEA CHIMMI YEA, SWALALA, SWA"
        
        image: hello-world
        tag: latest
        createdAt: 2021-09-23 23:47:57 +0000 UTC
  destination:
    server: https://kubernetes.default.svc
    namespace: danilicious-production