apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: us-east-1-danilicious-chimmi-production
  namespace: argocd
  annotations:
    godsAppName: chimmi
    godsApplicationType: Cron
    godsCluster: us-east-1
    godsTeamName: danilicious
    godsEnv: production
    godsEnvConfigurationVersion: c2c21a66fd2e93a2555d7306bba6d94bbcaec141
    godsImageTag: latest
spec:
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: 'https://github.com/gitopsdevsolutions/opinionated-charts'
    path: 'charts/base-cron-job'
    targetRevision: main
    
    helm:
      values: |
        env:
          DESCRIPTION: "CHIMMI CHIMMI YEA CHIMMI YEA CHIMMI YEA, SWALALALA"
        interval: "*/1 * * * *"
        image: hello-world
        tag: latest
        createdAt: 2021-09-23 23:47:57 +0000 UTC
  destination:
    server: https://kubernetes.default.svc
    namespace: danilicious-production