apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitopscd
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitopscd
  namespace: third-party-production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitopscd
subjects:
  - kind: ServiceAccount
    name: default
    namespace: gitopscd
