apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: us-east-1-danilicious-secret-production
  namespace: argocd
  annotations:
    godsAppName: secret
    godsApplicationType: Manifest
    godsCluster: us-east-1
    godsTeamName: danilicious
    godsEnv: production
    godsEnvConfigurationVersion: d45215cabacb7c2e5b747b907fa74dc76c22c42e
spec:
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: 'https://github.com/gitopsdevsolutions/opinionated-charts'
    path: 'charts/base-app'

    targetRevision: main
    plugin:
      name: argocd-vault-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: danilicious-production-namespace