apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: us-east-1-danilicious-secret-production
  namespace: argocd
  annotations:
    godsAppName: secret
    godsApplicationType: Manifest
    godsCluster: us-east-1
    godsTeamName: danilicious
    godsEnv: production
    godsEnvConfigurationVersion: 77431d3e67467fdd66a227ec34f09916d03abcfd
spec:
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: 'https://github.com/gitopsdevsolutions/gitops-cd-demo'
    path: 'live/us-east-1/danilicious/secret/production/manifest'

    targetRevision: main
    plugin:
      name: argocd-vault-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: danilicious-production-namespace